-- Asset Configuration File
-- Auto-generated by Fresh Voxel Engine Asset Manager
--
-- This file is automatically updated when assets are imported through
-- the asset management system (drag-and-drop or FileSystemWatcher)
--
-- Structure:
--   Assets.Textures[i] = { name, path }
--   Assets.Models[i] = { name, path }
--   Assets.Scripts[i] = { name, path }
--   Assets.Audio[i] = { name, path }
--   Assets.Shaders[i] = { name, path }
--   Assets.Configs[i] = { name, path }

Assets = {
    -- Texture assets
    Textures = {
        -- Example: {"grass", "Textures/grass.png"}
    },
    
    -- 3D Model assets
    Models = {
        -- Example: {"tree", "Models/tree.obj"}
    },
    
    -- Script assets (Lua, JavaScript, Python)
    Scripts = {
        -- Example: {"init", "Scripts/init.lua"}
    },
    
    -- Audio assets
    Audio = {
        -- Example: {"theme", "Audio/theme.mp3"}
    },
    
    -- Shader assets
    Shaders = {
        -- Example: {"basic", "Shaders/basic.glsl"}
    },
    
    -- Configuration files
    Configs = {
        -- Example: {"settings", "Configs/settings.json"}
    }
}

-- Return the Assets table for use by the engine
return Assets
